# Site settings
title: Thenextapps.com blog
email: thanhnam.it@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about my technical life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thenextapps.com" # the base hostname & protocol for your site
twitter_username: thanhnam_it
github_username:  thanhnamit

# Build settings
markdown: kramdown
