# Site settings
title: thenextapps.com blog
email: thanhnam.it@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young." - Henry Ford
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thenextapps.com" # the base hostname & protocol for your site
twitter_username: thanhnam_it
github_username:  thanhnamit

# Build settings
markdown: kramdown
