# Site settings
title: TheNextApps
email: thenextapps@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  B2B Commerce Experts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thenextapps.com" # the base hostname & protocol for your site
twitter_username: thenextapps
github_username:  thenextapps

# Build settings
markdown: kramdown